openapi: 3.0.3
info:
  title: Ekatteproject
  version: 1.0.0
  description: |
    Този проект зарежда и вкарва данни от официалните **ЕКАТТЕ** файлове, 
    предоставени от Националния статистически институт ([NSI EKATTE](https://www.nsi.bg/nrnm/ekatte/index)), 
    в **PostgreSQL** база данни. Освен това предоставя уеб интерфейс за търсене,създаване,триене и 
    обновяване на информация за селища. С възможностите да се сортират по колони и да се изтегля статистика 
    с текущия брой селища, общини, кметства и области.

    ## Основни технологии

    - **Docker** – За контейнеризация на базите данни, в които ще се съхранява информацията.
    - **Node.js** – За backend логиката.
      - **Vitest** - Използва се за писане на unit тестове.
      - **Supertest** - за integration тестове съвместно с Vitest
      - **Nodemon** - Автоматично презарежда приложението при промяна в кода.
      - **Dotenv** - Зарежда environment променливи от .env файл
      - **Exceljs** - За извеждане на статистиките в CSV формат и XLSX за Microsoft Excel
    - **PostgreSQL** – За комуникация между backend-а и базите данни.

    ## Цикъл на програмата

    Приложението започва от `index.js`, където създава сървър чрез вградения HTTP модул на Node.js.
    При създаването на сървъра се извиква основния handler, който на своя страна извиква всички middlewares 
    и накрая `routing_dispatcher`.`routing_dispatcher` определя към кой контролер да се насочи заявката в 
    зависимост от метода на HTTP заявката. При неуспех на изпълнението на заявката, в `routing_dispatcher` 
    се използва `try-catch`, като грешката се обработва от функцията `error_handle`. 

    Заявките, който се приемат до момента са описани по долу:

servers:
  - url: http://localhost:3000
    description: Локален сървър

paths:
  paths:
  /api/init:
    get:
      summary: Инициализация на базите данни
      description: |
        Извиква функцията bulk_inserts_from_json за първоначално попълване на данните.
      responses:
        "200":
          description: Данните са инициализирани успешно
        "500":
          description: Възникна грешка при инициализацията

  /api/villages:
    get:
      summary: Връща всички селища
      description: Извлича всички редове от таблицата Villages.
      responses:
        "200":
          description: Успешно получени данни
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Village"
        "400":
          description: Грешка при заявката

  /api/init-statistics:
    get:
      summary: Връща статистики за таблиците
      description: Извиква getStatistics и връща информация за брой редове и други статистики.
      responses:
        "200":
          description: Успешно получени статистики
          content:
            application/json:
              schema:
                type: object
        "500":
          description: Грешка при изчисляването на статистиките

  /search/villages:
    get:
      summary: Търсене на селища
      description: Връща информация за селища според подадените query параметри.
      parameters:
        - in: query
          name: bgName
          schema:
            type: string
          description: Име на селището на български език за търсене
        - in: query
          name: enName
          schema:
            type: string
          description: Име на селището на английски език за търсене
      responses:
        "200":
          description: Успешно получени резултати
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Village"
        "400":
          description: Невалидни параметри на заявката

  /districts-names:
    get:
      summary: Връща имената на областите
      description: Връща списък с всички имена на области от таблицата District.
      responses:
        "200":
          description: Успешно получени данни
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string

  /townships-names:
    get:
      summary: Връща имената на общините
      description: Връща списък с всички имена на общини от таблицата Township.
      responses:
        "200":
          description: Успешно получени данни
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string

  /sorted/villages:
    get:
      summary: Сортиране на селища
      description: Връща сортираните селища според подадените параметри. Ако параметрите са невалидни, връща грешка.
      parameters:
        - in: query
          name: id
          schema:
            type: string
            enum: [ASC, DESC]
          description: Сортиране по ID на селището (ASC - възходящо, DESC - низходящо)
        - in: query
          name: nameBG
          schema:
            type: string
            enum: [ASC, DESC]
          description: Сортиране по име на селището на български (ASC - възходящо, DESC - низходящо)
        - in: query
          name: nameEN
          schema:
            type: string
            enum: [ASC, DESC]
          description: Сортиране по име на селището на английски (ASC - възходящо, DESC - низходящо)
        - in: query
          name: district
          schema:
            type: string
            enum: [ASC, DESC]
          description: Сортиране по район (ASC - възходящо, DESC - низходящо)
        - in: query
          name: township
          schema:
            type: string
            enum: [ASC, DESC]
          description: Сортиране по община (ASC - възходящо, DESC - низходящо)
        - in: query
          name: cityhall
          schema:
            type: string
            enum: [ASC, DESC]
          description: Сортиране по кметство (ASC - възходящо, DESC - низходящо)
      responses:
        "200":
          description: Успешно сортирани данни
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Village"
        "400":
          description: Невалидни параметри

  /export/excel:
    get:
      summary: Експорт в Excel
      description: Връща данните за селища в XLSX формат.
      responses:
        "200":
          description: Файлът е генериран успешно
          content:
            application/vnd.openxmlformats-officedocument.spreadsheetml.sheet:
              schema:
                type: string
                format: binary

  /export/csv:
    get:
      summary: Експорт в CSV
      description: Връща данните за селища в CSV формат.
      responses:
        "200":
          description: Файлът е генериран успешно
          content:
            text/csv:
              schema:
                type: string
                format: binary

  /api/create-data:
    post:
      summary: Създаване на ново селище
      description: >
        Създава ново селище. Handlerът първо взема последното ID от таблица
        Villages, извлича district_id и township_id по изпратените имена,
        и след това добавя ред в таблицата чрез insert_row_into_village.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateVillageRequest"
      responses:
        "200":
          description: Селището е създадено успешно
          content:
            text/plain:
              schema:
                type: string
                example: "Request was successful"
        "400":
          description: Невалидни данни
        "422":
          description: Липсващо задължително поле или невалиден input

  /api/edit-data:
    put:
      summary: Редактиране на селище
      description:
        Извиква конкретния handler "updateVillageHandler", който на свой
        ред извиква функцията "update_village" за изтриване на селище
        от src/model/village.js
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateVillageRequest"
      responses:
        "200":
          description: Селището е редактирано успешно
          content:
            text/plain:
              schema:
                type: string
                example: "Request was successful"
        "400":
          description: Невалидни данни

  /api/delete-data:
    delete:
      summary: Изтриване на селище
      description:
        Извиква конкретния handler, който на свой ред извиква функцията
        "delete_village_row" за изтриване на селище от src/model/village.js
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                  description: ID на селището за изтриване
                  example: "00101"
      responses:
        "200":
          description: Селището е изтрито успешно
          content:
            text/plain:
              schema:
                type: string
                example: "Request was successful"
        "404":
          description: Селището не е намерено

components:
  schemas:
    UpdateVillageRequest:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        name_en:
          type: string
        township_name:
          type: string
        district_name:
          type: string
      required:
        - id
        - name
        - name_en
        - township_name
        - district_name

    CreateVillageRequest:
      type: object
      description: Заявка за създаване на селище
      properties:
        name:
          type: string
          description: Име на селището на български
          example: "София-център-Село"
        name_en:
          type: string
          description: Име на селището на английски
          example: "Sofia Center Village"
        township_name:
          type: string
          description: Име на общината
          example: "София-център"
        district_name:
          type: string
          description: Име на областта
          example: "София"
      required:
        - name
        - name_en
        - township_name
        - district_name

    District:
      type: object
      description: Области
      properties:
        id:
          type: string
          description: Уникален код за идентификация
          minLength: 3
          maxLength: 3
          example: "001"
        name:
          type: string
          description: Име на областта на български
          maxLength: 25
          example: "София"
        name_en:
          type: string
          description: Име на областта на английски
          maxLength: 25
          example: "Sofia"
        center_id:
          type: string
          description: Код на областния център
          minLength: 5
          maxLength: 5
          example: "00101"
      required:
        - id
        - name
        - name_en
        - center_id

    Township:
      type: object
      description: Общини
      properties:
        id:
          type: string
          description: Уникален код за идентификация (district_id + код)
          minLength: 5
          maxLength: 5
          example: "00101"
        name:
          type: string
          description: Име на общината на български
          maxLength: 25
          example: "София-център"
        name_en:
          type: string
          description: Име на общината на английски
          maxLength: 25
          example: "Sofia Center"
        district_id:
          type: string
          description: Код на областта
          minLength: 3
          maxLength: 3
          example: "001"
        center_id:
          type: string
          description: Код на общинския център
          minLength: 5
          maxLength: 5
          example: "00101"
      required:
        - id
        - name
        - name_en
        - district_id
        - center_id

    Village:
      type: object
      description: Селища
      properties:
        id:
          type: string
          description: Уникален код за идентификация
          minLength: 5
          maxLength: 5
          example: "00101"
        name:
          type: string
          description: Име на селището на български
          maxLength: 70
          example: "София-център-Село"
        name_en:
          type: string
          description: Име на селището на английски
          maxLength: 70
          example: "Sofia Center Village"
        township_id:
          type: string
          description: Код на общината
          minLength: 5
          maxLength: 5
          example: "00101"
        district_id:
          type: string
          description: Код на областта
          minLength: 3
          maxLength: 3
          example: "001"
      required:
        - id
        - name
        - name_en
        - township_id
        - district_id

    Cityhall:
      type: object
      description: Кметства
      properties:
        id:
          type: string
          description: Уникален код за идентификация (township_id + код)
          minLength: 8
          maxLength: 8
          example: "00101001"
        name:
          type: string
          description: Име на кметството на български
          maxLength: 25
          example: "София-център-Кметство"
        name_en:
          type: string
          description: Име на кметството на английски
          maxLength: 25
          example: "Sofia Center Cityhall"
        township_id:
          type: string
          description: Код на общината
          minLength: 5
          maxLength: 5
          example: "00101"
      required:
        - id
        - name
        - name_en
        - township_id
